### ISSUE TITLE
It doesn't work with tns-core-modules v6.2.1

### ISSUE THREAD

**Issue by darkyelox** [elvticc/nativescript-getters#1]
Maybe you must migrate to nativescript 6.2

**Comment by bgrand-ch** [comment]
Thank you for this information. Sorry for the response time, I have not been notified by Github of the opening of a new issue. I'll fix that tomorrow!

**Comment by bgrand-ch** [comment]
WIP

**Comment by bgrand-ch** [comment]
Problem solved. I am trying to configure [Release it](https://github.com/release-it/release-it) to publish the new version on Github and NPM.
