### ISSUE TITLE
New issue

### ISSUE THREAD

**Issue by darko-bw** [elvticc/nativescript-getters#14]
Hi @bgrand-ch 

I have got somehow a few issues when building the ios app:

warning: duplicate output file '/Users/username/Library/Developer/Xcode/DerivedData/myapp-chfrkjiusakzaccbyurwhkhlehcn/Build/Intermediates.noindex/ArchiveIntermediates/myapp/InstallationBuildProductsLocation/Applications/myapp.app/Frameworks/TNSWidgets.framework' on task: PBXCp /Users/username/Dropbox/oxiti/myapp/node_modules/nativescript-getters/node_modules/@nativescript/core/platforms/ios/TNSWidgets.xcframework/ios-arm64/TNSWidgets.framework /Users/username/Library/Developer/Xcode/DerivedData/myapp-chfrkjiusakzaccbyurwhkhlehcn/Build/Intermediates.noindex/ArchiveIntermediates/myapp/InstallationBuildProductsLocation/Applications/myapp.app/Frameworks/TNSWidgets.framework (in target 'myapp' from project 'myapp')

warning: duplicate output file '/Users/username/Library/Developer/Xcode/DerivedData/myapp-chfrkjiusakzaccbyurwhkhlehcn/Build/Intermediates.noindex/ArchiveIntermediates/myapp/InstallationBuildProductsLocation/Applications/myapp.app/Frameworks/TNSWidgets.framework/TNSWidgets' on task: PBXCp /Users/username/Dropbox/oxiti/myapp/node_modules/nativescript-getters/node_modules/@nativescript/core/platforms/ios/TNSWidgets.xcframework/ios-arm64/TNSWidgets.framework /Users/username/Library/Developer/Xcode/DerivedData/myapp-chfrkjiusakzaccbyurwhkhlehcn/Build/Intermediates.noindex/ArchiveIntermediates/myapp/InstallationBuildProductsLocation/Applications/myapp.app/Frameworks/TNSWidgets.framework (in target 'myapp' from project 'myapp')

warning: duplicate output file '' on task: PBXCp /Users/username/Dropbox/oxiti/myapp/node_modules/nativescript-getters/node_modules/@nativescript/core/platforms/ios/TNSWidgets.xcframework/ios-arm64/TNSWidgets.framework /Users/username/Library/Developer/Xcode/DerivedData/myapp-chfrkjiusakzaccbyurwhkhlehcn/Build/Intermediates.noindex/ArchiveIntermediates/myapp/InstallationBuildProductsLocation/Applications/myapp.app/Frameworks/TNSWidgets.framework (in target 'myapp' from project 'myapp')

Do you know what may cause them? All of the referring to nativescript-getters

**Comment by bgrand-ch** [comment]
Hello @basil-wolf 

Thanks for your issue.

My error on the latest release: I added `dependencies` instead of `peerDependencies`...

This creates a conflict with a private `node_modules` when installing the package.

Sources:
- https://nodejs.org/es/blog/npm/peer-dependencies/
- https://docs.npmjs.com/about-semantic-versioning
- https://medium.com/angular-in-depth/npm-peer-dependencies-f843f3ac4e7f

---

To resolve this error:

1. `ns clean`
2. `nativescript-getters` to `0.3.4`
3. `ns debug ios`

**Comment by darko-bw** [comment]
Thank you @bgrand-ch, awesome news! Is it going to be a future proof as I can see in your package.json ns-core is aimed to 8.0.2 only, what about next versions?

**Comment by darko-bw** [comment]
And actually @bgrand-ch , sorry for not telling you I have checked 0.3.4 on my project and it is working fine.

**Comment by bgrand-ch** [comment]
The plugin will remain functional in version `0.3.4` during all versions of `@nativescript/core@8.x.x`.

When the `@nativescript/core@9.x.x` will released, I will modify the plugin again to make it functional.

In the meantime, I will continue to optimize it and add new features. See project 2: https://github.com/bgrand-ch/nativescript-getters/projects/2

Thanks for your tests, have a nice evening.

**Comment by darko-bw** [comment]
Thanks so much @bgrand-ch
