### ISSUE TITLE
Issue with NativeScript 8

### ISSUE THREAD

**Issue by darko-bw** [elvticc/nativescript-getters#3]
As NS8 has been released a few days ago, there were some changes to the Tabs and Bottom Navigation:

https://blog.nativescript.org/nativescript-8-announcement/index.html#important-note-about-bottomnavigation-and-tabs

When using the latest version of the nativescript-getters, there is an error complaining about line 5 in getters.ts -> TabNavigationBase, after removing this line everything works fine.

Would you be able to update your plugin any time soon? Many thanks.

**Comment by bgrand-ch** [comment]
@basil-wolf Hello, thanks for this information. I will be completely revising `nativescript-getters` over the next two weeks, it will be fully functional with the latest version of NativeScript on the evening of April 18th.

**Comment by bgrand-ch** [comment]
WIP

Progression: https://github.com/bgrand-ch/nativescript-getters/projects/1
Pull request: #4

**Comment by darko-bw** [comment]
Hi @bgrand-ch thank you so much for the wip. It is much appreciated

**Comment by bgrand-ch** [comment]
Monorepo is a long way to implement (https://github.com/bgrand-ch/nativescript-getters/pull/4). I open a new PR https://github.com/bgrand-ch/nativescript-getters/pull/5 to just migrate to NS8 and apply your fix.

**Comment by darko-bw** [comment]
Thank you @bgrand-ch when do you think the release with the fix will be available?

**Comment by bgrand-ch** [comment]
I work on it this noon and this early evening.
Normally, this evening, if I don't have a problem :wink:

**Comment by bgrand-ch** [comment]
[v.0.3.0](https://github.com/bgrand-ch/nativescript-getters/releases/tag/v0.3.0) publish to NPM

@basil-wolf OK for me in local dev. Could you test that everything is working fine please?

**Comment by darko-bw** [comment]
Hi @bgrand-ch when I install the plugin it says: **nativescript-getters is not a valid NativeScript plugin. Verify that the plugin package.json file contains a nativescript key and try again.**

**Comment by bgrand-ch** [comment]
Thanks, I will fix this error in few minutes, sorry for the inconvenience

**Comment by bgrand-ch** [comment]
@basil-wolf Could you test again please?

**Comment by darko-bw** [comment]
Hi @bgrand-ch the installation went well but on a build, there is a few errors: single file module using description file: /Users/test/package.json (relative path: ./node_modules/nativescript-getters) no extension  /Users/test/node_modules/nativescript-getters doesn't exist

**Comment by darko-bw** [comment]
And a few of these: **/Users/test/myapp/node_modules/nativescript-getters/index doesn't exist** including .ios.ts, .ios.css, .ios.json etc

**Comment by bgrand-ch** [comment]
I wanted to go fast, but it's missed. I really have to dive back into it and do some real local testing. I'm busy this weekend, but I'll do my best this week. Thanks for your tests 🙂

**Comment by darko-bw** [comment]
It is no problem @bgrand-ch , I completely understand and really appreciate your hard work on this plugin. It is one of the best! Thank you.

**Comment by bgrand-ch** [comment]
[v.0.3.2](https://github.com/bgrand-ch/nativescript-getters/releases/tag/v0.3.2) publish to NPM

@basil-wolf OK for me in local with `./demo`. Could you test that everything is working fine please? :innocent:

**Comment by darko-bw** [comment]
Hi @bgrand-ch , thanks for a quick update, I have just tested the plugin and with my biggest pleasure I can confirm that it working absolutely flawless. Thanks a lot.
